# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Table_no', models.CharField(max_length=50)),
                ('Original_win_loss', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('Final_win_loss', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('Turnover', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('Player', models.CharField(default='', max_length=100)),
                ('Nickname', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
