# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 11:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('player', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('txt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('results', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('after_rake', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('win', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('turnover', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.Account')),
            ],
            options={
                'permissions': (('can_upload', 'Can upload'),),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.Agent'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
